import { faker } from '@faker-js/faker';
import { Inter } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Autoplay, Navigation, Pagination } from 'swiper';
import 'swiper/css';
import 'swiper/css/autoplay';
import 'swiper/css/pagination';
import { Swiper, SwiperSlide } from 'swiper/react';

import Words from './Words';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const img: string = faker.image.sports();
	console.log(img);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="mx-auto min-h-screen max-w-4xl">
				<nav className="flex w-full items-center justify-between pt-6">
					<div>
						<div className="cursor-pointer rounded bg-orange-700 px-3 pb-2 pt-1 font-[300] transition hover:bg-orange-600 active:scale-90">
							{Words.signIn}
						</div>
					</div>
					<div className="flex flex-row-reverse items-center">
						<Link href={'/'} className="cursor-pointer pl-12">
							<div className="animate-hue-animation rounded-full bg-orange-900 px-2 pb-2 pt-1 font-[700]">
								بدو
							</div>
						</Link>
						<div className="flex space-x-6 font-[200]">
							<div className="cursor-pointer opacity-70 transition hover:opacity-100">
								{Words.nav3}
							</div>
							<div className="cursor-pointer opacity-70 transition hover:opacity-100">
								{Words.nav2}
							</div>
							<div className="cursor-pointer opacity-70 transition hover:opacity-100">
								{Words.nav1}
							</div>
						</div>
					</div>
				</nav>
				<div className="mt-8 w-full">
					<Swiper
						pagination={{ clickable: true }}
						slidesPerView={'auto'}
						centeredSlides={true}
						spaceBetween={-100}
						modules={[Pagination, Autoplay, Navigation]}
						loop={true}
						navigation={true}
						autoplay={{
							delay: 2500,
							disableOnInteraction: false
						}}
					>
						<SwiperSlide>
							<div className="h-52 w-[838px] pl-16">
								<Link href={'/'}>
									<Image
										src={img}
										alt="random img"
										width={0}
										height={0}
										sizes="100vw"
										priority
										className="h-full w-full rounded"
									/>
								</Link>
							</div>
						</SwiperSlide>
						<SwiperSlide>
							<div className="h-52 w-[838px] pl-16">
								<Link href={'/'}>
									<Image
										src={img}
										alt="random img"
										width={0}
										height={0}
										sizes="100vw"
										priority
										className="h-full w-full rounded"
									/>
								</Link>
							</div>
						</SwiperSlide>
						<SwiperSlide>
							<div className="h-52 w-[838px] pl-16">
								<Link href={'https://www.google.com/'}>
									<Image
										src={img}
										alt="random img"
										width={0}
										height={0}
										sizes="100vw"
										priority
										className="h-full w-full rounded"
									/>
								</Link>
							</div>
						</SwiperSlide>
						<SwiperSlide>
							<div className="h-52 w-[838px] pl-16">
								<Link href={'/'}>
									<Image
										src={img}
										alt="random img"
										width={0}
										height={0}
										sizes="100vw"
										priority
										className="h-full w-full rounded"
									/>
								</Link>
							</div>
						</SwiperSlide>
					</Swiper>
				</div>
			</main>
		</>
	);
}
